package com.mycompany.guessmeapp;

import java.util.Random;

public class MainScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());
    private int randomNumber;
    private int userAttempts;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        this.randomNumber = this.generateRandomNumber();
        this.userAttempts = 0;
    }
    
    private int generateRandomNumber () {
        Random random = new Random();
        
        int number = random.nextInt(1001);
        
        return number;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainTitle = new javax.swing.JLabel();
        lblAttempts = new javax.swing.JLabel();
        lblAttemptsCount = new javax.swing.JLabel();
        lblSecretNumber = new javax.swing.JLabel();
        lblTip = new javax.swing.JLabel();
        lblGuessLabel = new javax.swing.JLabel();
        inputUserNumber = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        btnTip = new javax.swing.JButton();
        lblGreaterTip = new javax.swing.JLabel();
        lblLessTip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblMainTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMainTitle.setText("Guess Me");

        lblAttempts.setText("Attempts:");

        lblAttemptsCount.setText("0");

        lblSecretNumber.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSecretNumber.setText("?");

        lblTip.setEnabled(false);

        lblGuessLabel.setText("Guess:");

        inputUserNumber.setText("Enter a Number");
        inputUserNumber.setToolTipText("");
        inputUserNumber.setMinimumSize(new java.awt.Dimension(80, 22));
        inputUserNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserNumberActionPerformed(evt);
            }
        });

        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnTip.setText("Tip");
        btnTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipActionPerformed(evt);
            }
        });

        lblGreaterTip.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblGreaterTip.setText("+");
        lblGreaterTip.setEnabled(false);

        lblLessTip.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLessTip.setText("-");
        lblLessTip.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMainTitle)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSecretNumber)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAttempts)
                                .addGap(53, 53, 53)
                                .addComponent(lblAttemptsCount))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGreaterTip)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblLessTip))))
                    .addComponent(lblTip))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuess))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGuessLabel)
                        .addGap(18, 18, 18)
                        .addComponent(inputUserNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblMainTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttempts)
                    .addComponent(lblAttemptsCount))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblSecretNumber)
                        .addGap(60, 60, 60)
                        .addComponent(lblTip))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblGreaterTip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLessTip)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGuessLabel)
                    .addComponent(inputUserNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTip)
                    .addComponent(btnGuess))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputUserNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserNumberActionPerformed

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        // TODO add your handling code here:
        
        String userInput = inputUserNumber.getText().trim();
        int randomNumber = this.getRandomNumber();
        
        lblLessTip.setEnabled(false);
        lblGreaterTip.setEnabled(false);
    
        try {
            int number = Integer.parseInt(userInput);

            if (number != randomNumber) {
                lblTip.setText("Wrong number!");
                
                if (number > randomNumber) {
                    lblLessTip.setEnabled(rootPaneCheckingEnabled);
                    lblTip.setText("Try a LOWER number");
                } else {
                    lblGreaterTip.setEnabled(rootPaneCheckingEnabled);
                    lblTip.setText("Try a HIGHER number");
                }
                
                this.setUserAttempts();
                int currentUserAttempts = this.getUserAttempts();
                
                lblAttemptsCount.setText(String.valueOf(currentUserAttempts));
            } else {
                lblTip.setText("Congratulations!");
                
                lblSecretNumber.setText(String.valueOf(randomNumber));
                
                btnGuess.setEnabled(false);
                btnTip.setEnabled(false);
            }
        } catch (NumberFormatException e) {
            lblTip.setText("Please input a Number");
        }
    }//GEN-LAST:event_btnGuessActionPerformed

    private void btnTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipActionPerformed
        // TODO add your handling code here:
        
        int randomNumber = this.getRandomNumber();
        
        String text = "";
        
        if (randomNumber % 2 == 0) {
           text = "It's an EVEN number";
        } else {
            text = "It's an ODD number";
        }
                
        lblTip.setText(text);
    }//GEN-LAST:event_btnTipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }
    
    private int getRandomNumber () {
        return this.randomNumber;
    }
    
    private int getUserAttempts () {
        return this.userAttempts;
    }
    
    private void setUserAttempts () {
        this.userAttempts++;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnTip;
    private javax.swing.JTextField inputUserNumber;
    private javax.swing.JLabel lblAttempts;
    private javax.swing.JLabel lblAttemptsCount;
    private javax.swing.JLabel lblGreaterTip;
    private javax.swing.JLabel lblGuessLabel;
    private javax.swing.JLabel lblLessTip;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblSecretNumber;
    private javax.swing.JLabel lblTip;
    // End of variables declaration//GEN-END:variables
}
